# a minimal workspace config file
# use ws_validate_config to validate a config file
clustername: testcluster		# some label to distinguish clusters, is shown in emails
smtphost: localhost			# SMTP host where mail can be deliverd on port 25
admins: [root]				# users listed here can see all workspaces
adminmail: [root@localhost]		# admin users email addresses getting warnings/error reports
mail_from: root@testcluster		# sender email address
dbgid: 9999				# a GID to be used, can be e.g. daemon or a special  GID
dbuid: 9999				# a UID to be used
default: lustre				# default filesystem to use for all users
durationdefault: 3			# default duration if users does not specify
deldir_timeout: 60			# timeout for deletion during expiration for a single workspace
filesystems:				# now the filesystem specific options
  lustre:					# a label
    duration: 30				# max duration
    keeptime: 4					# time in days to keep after expiration
    maxextensions: 5				# max numner of extensiosn
    database: /lustre/ws-db			# the database directory
    spaces: [/lustre/ws]			# where the workspaces are created
    deleted: .removed				# subdirectory name for released/expired workspaces, in DB and space
