.TH ws_stat 1 "July 2025" "USER COMMANDS"

.SH NAME
ws_stat \- list workspaces

.SH SYNOPSIS
.B ws_stat
[\-h] [\-V] [\-F FILESYSTEM] [\-g] [\-r] [\-N] [\-R] [\-C] [\-m DEPTH] [\-t THREADS] [PATTERN]

.SH DESCRIPTION
Show statistics for
.B workspaces
of the calling user.
The output can be restricted to
.B workspaces
in a certain FILESYSTEM, matching a certain PATTERN, and can be sorted according to different criterias.

The output includes number of files, symlinks and directories of the workspace and the total number of bytes (sum of filesizes).
On Lustre Filesystems, this uses the size on metedata if possible which is cheaper than stat() calls and therefor
.B du.

.B PATTERN
is a unix glob expression, * matches all characters, please be aware that quoting might be required
by your shell.


The idea of the
.B workspace
is to allow the administrator to keep control of filespace in working filesystems,
and to avoid the situations that data of past and finished projects/jobs is idling for
ever on disks. A user can create and dispose arbitrary number of workspaces, they are cheap,
and can be created e.g. for each job.

From the system side,
.B workspaces
will be deleted after beeing expired. A friendly user can release workspaces before the expiration
date using
.B ws_release
which will mark the
.B workspace
for future deletion.

Deletion is probably a task done once a night and not immediately.

If a
.B workspace
was forgotten and expired, it might make sense to contact the administrator,
as he probaly can restore a workspace for some time, if disk space is not low.
Check if
.ws_restore
is available allowing you to restore workspaces on your own.

The tool uses parallel processing to speed up statistics gathering on large workspaces.
By default, the number of threads is determined automatically based on the hardware.
The parallel directory traversal uses a depth-limited approach to balance memory usage
with parallelism efficiency.

.PP

.SH OPTIONS
.TP
\-h
display usage help text
.TP
\-V
show version and build information
.TP
\-F
select the filesystem to list the workspaces from.
.TP
\-g
show group-workspaces visible for current group in addition to own workspaces
.TP
\-N
sort according to names of workspaces
.TP
\-R
sort according to remaining time of workspaces
.TP
\-C
sort according to creation date of workspaces
.TP
\-r
invert the sorting of \-N, \-C or \-R
.TP
\-m DEPTH
set maximum depth for parallel directory traversal.
At depths beyond this limit, subdirectories are processed serially.
Default: auto-calculated based on thread count (min(6, max(3, threads/4))).
Minimum value: 3.
.TP
\-t THREADS
set the number of threads for parallel operation.
This affects both workspace-level and directory-level parallelism.
Default: hardware_concurrency (number of CPU cores).
Minimum enforced value: 4 for effective parallelism.
Environment variable WS_THREADS can also be used.


.SH AUTHOR
Written by Holger Berger

.SH SEE ALSO
ws_list, ws_allocate, ws_release, ws_restore, ws_find
